package(default_visibility = ["//src/framework:__subpackages__", "//src/tests:__subpackages__"])

cc_library(
    name = "graph_profiler",
    srcs = [
        "clock.cc",
        "graph_profiler.cc",
        "profile_writer.cc",
        "time_histogram.cc",
    ],
    hdrs = [
        "clock.h",
        "graph_profiler.h",
        "profiler_config.h",
        "profile_writer.h",
        "time_histogram.h",
    ],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/time",
        "@graph_runtime//src/framework/public:hook_header",
    ],
)
