package(default_visibility = ["//src/framework:__subpackages__", "//src/tests:__subpackages__"])

cc_library(
    name = "hook",
    srcs = ["factory.cc"],
    hdrs = ["factory.h"],
    deps = ["@graph_runtime//src/framework/public:hook_header"],
)

cc_library(
    name = "log_core",
    srcs = ["logger.cc"],
    hdrs = ["logger.h"],
    copts = [
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden",
    ],
    deps = [
        "@graph_runtime//src/framework/utils:hook",
        "@com_google_absl//absl/synchronization",
    ],
)
