package(default_visibility = ["//visibility:public"])

cc_library(
    name = "types",
    hdrs = ["types.h"],
    deps = [
        "@com_google_absl//absl/status",
    ],
)

cc_library(
    name = "side_packet",
    hdrs = ["side_packet.h"],
    deps = [
        "//src/stream:packet",
        "//src/public:types",
    ],
)

cc_library(
    name = "graph_builder",
    srcs = ["graph_builder.cc"],
    hdrs = ["graph_builder.h"],
    deps = [
        ":runtime_shared",
        "//src/config:config",
        "//src/config:graph_config",
        "//src/scheduler:scheduler",
        "//src/scheduler:thread_pool_executor",
        "//src/node:node_factory_registry",
    ],
)

cc_library(
    name = "runtime_shared",
    hdrs = [
        "graph_runtime.h",
        "types.h",
        "side_packet.h",
    ],
    deps = [
        "//src/config:graph_config",
        "//src/scheduler:scheduler",
        "//src/node:graph_context",
        "//src/public:types",
        "//src/stream:packet",
    ],
)

cc_library(
    name = "runtime",
    srcs = ["graph_runtime.cc"],
    deps = [
        ":graph_builder",
        ":runtime_shared",
        "//src/scheduler:scheduler",
        "//src/config:graph_config",
        "//src/public:types",
    ],
)
