package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "log_core",
    srcs = ["logger.cc"],
    hdrs = ["logger.h"],
    copts = [
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden",
    ],
    deps = [
        "@graph_runtime//src/hook:hook",
        "@com_google_absl//absl/synchronization",
    ],
)
