package(default_visibility = ["//src/framework:__subpackages__", "//src/tests:__subpackages__"])

cc_library(
    name = "executor",
    hdrs = ["executor.h"],
    deps = [
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "input_stream_handler",
    srcs = ["input_stream_handler.cc"],
    hdrs = ["input_stream_handler.h"],
    deps = [
        ":executor",
        "@graph_runtime//src/framework/stream:input_stream_manager",
        "@graph_runtime//src/framework/node:node_base",
        "@graph_runtime//src/framework/node:graph_context",
        "@graph_runtime//src/framework/public:types",
    ],
)

cc_library(
    name = "thread_pool_executor",
    srcs = ["thread_pool_executor.cc"],
    hdrs = ["thread_pool_executor.h"],
    deps = [
        ":executor",
    ],
)

cc_library(
    name = "counters",
    hdrs = ["counters.h"],
)

cc_library(
    name = "scheduler_queue",
    srcs = ["scheduler_queue.cc"],
    hdrs = ["scheduler_queue.h"],
    deps = [
        ":executor",
        "@graph_runtime//src/framework/node:graph_context",
        "@graph_runtime//src/framework/node:node_base",
        "@graph_runtime//src/framework/profiler:graph_profiler",
        "@graph_runtime//src/framework/stream:output_stream_handler",
        "@graph_runtime//src/framework/utils:logger",
        ":counters",
    ],
)

cc_library(
    name = "scheduler",
    srcs = ["scheduler.cc"],
    hdrs = ["scheduler.h"],
    deps = [
        ":executor",
        ":scheduler_queue",
        ":thread_pool_executor",
        ":input_stream_handler",
        ":counters",
        "@graph_runtime//src/framework/profiler:graph_profiler",
        "@graph_runtime//src/framework/utils:logger",
        "@graph_runtime//src/framework/stream:input_stream_manager",
        "@graph_runtime//src/framework/stream:input_stream",
        "@graph_runtime//src/framework/stream:output_stream_handler",
        "@graph_runtime//src/framework/node:graph_context",
        "@graph_runtime//src/framework/node:node_factory_registry",
        "@graph_runtime//src/framework/node:node_base",
    ],
)
