#!/bin/bash
# Platform setup script for Graph Runtime
# Detects the host platform and writes .user.bazelrc so that bazel
# configurations work out of the box with the correct platform target.
#
# Usage:
#   ./tools/platform_setup.sh          # auto-detect and write .user.bazelrc
#   ./tools/platform_setup.sh --quiet  # suppress output, only error on failure
#
# The generated .user.bazelrc is git-ignored and machine-local.
# See .bazelrc for the try-import chain:
#   .bazelrc -> try-import .configure.bazelrc -> try-import .user.bazelrc

set -e

QUIET=false
if [ "${1:-}" = "--quiet" ]; then
    QUIET=true
fi

log() {
    if ! $QUIET; then
        echo "$@"
    fi
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
USER_BAZELRC="$PROJECT_DIR/.user.bazelrc"

cat > "$USER_BAZELRC" <<EOF
# Auto-generated by tools/platform_setup.sh on $(LC_ALL=C date)
# Platform: $(uname -s) $(uname -m)
# DO NOT EDIT — this file is machine-local and regenerated by platform_setup.sh.
# Add persistent customizations to .bazelrc instead.

EOF

# ---- Platform detection ----

OS="$(uname -s)"
ARCH="$(uname -m)"

if [ "$OS" = "Darwin" ]; then
    if [ "$ARCH" = "arm64" ]; then
        PLATFORM_CONFIG="macos_arm64"
        log "  Platform:    macOS arm64 (Apple Silicon)"
        log "  Config:      bazel build //... --config=macos_arm64"
    else
        PLATFORM_CONFIG="macos_x86_64"
        log "  Platform:    macOS x86_64 (Intel)"
        log "  Config:      bazel build //... --config=macos_x86_64"
    fi
else
    if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
        PLATFORM_CONFIG="linux_aarch64"
        log "  Platform:    Linux aarch64"
        log "  Config:      bazel build //... --config=linux_aarch64"
    else
        PLATFORM_CONFIG="linux_x86_64"
        log "  Platform:    Linux x86_64"
        log "  Config:      bazel build //... --config=linux_x86_64"
    fi
fi

cat >> "$USER_BAZELRC" <<EOF
# Host platform (auto-detected)
build --config=$PLATFORM_CONFIG

EOF

# ---- Optional: Android SDK/NDK detection (when android_ndk_repository is added) ----
# Reserved for future cross-compilation support.
# See atlas project (tools/platform_setup.sh) for reference implementation.

log ""
log "Wrote $USER_BAZELRC"
