package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "string_pipeline",
    srcs = ["string_pipeline.cc"],
    deps = [
        "@graph_runtime//src/framework/public:runtime",
    ],
)

cc_binary(
    name = "custom_parser",
    srcs = ["custom_parser.cc"],
    deps = [
        "@graph_runtime//src/framework/config:config",
        "@graph_runtime//src/framework/public:runtime",
    ],
)

cc_binary(
    name = "log_intercept_demo",
    srcs = ["log_intercept_demo.cc"],
    deps = [
        "@graph_runtime//src/framework/public:runtime",
    ],
)

cc_binary(
    name = "string_pipeline_json",
    srcs = ["string_pipeline_json.cc"],
    deps = [
        "@graph_runtime//src/framework/public:runtime",
    ],
)

cc_binary(
    name = "async_pipeline_demo",
    srcs = ["async_pipeline_demo.cc"],
    deps = [
        "@graph_runtime//src/framework/public:runtime",
    ],
)

cc_binary(
    name = "add_packet_demo",
    srcs = ["add_packet_demo.cc"],
    deps = [
        "@graph_runtime//src/framework/public:runtime",
    ],
)
