package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "string_pipeline",
    srcs = ["string_pipeline.cc"],
    deps = [
        "//src/public:runtime",
    ],
)

cc_binary(
    name = "custom_parser",
    srcs = ["custom_parser.cc"],
    deps = [
        "//src/config:config",
    ],
)
