package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "string_pipeline",
    srcs = ["string_pipeline.cc"],
    deps = [
        "//src/public:runtime",
    ],
)

cc_binary(
    name = "custom_parser",
    srcs = ["custom_parser.cc"],
    deps = [
        "//src/config:config",
    ],
)

cc_binary(
    name = "string_pipeline_json",
    srcs = ["string_pipeline_json.cc"],
    deps = [
        "//src/config/json:json_parser",
        "//src/config:config",
        "//src/node:node_base",
        "//src/node:graph_context",
        "//src/stream:packet",
        "//src/stream:timestamp",
    ],
)
