package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "graph_config",
    hdrs = ["graph_config.h"],
    deps = [
        "@graph_runtime//src/framework/node:node_options",
    ],
)

cc_library(
    name = "config",
    hdrs = [
        "i_graph_config_parser.h",
        "config_validator.h",
        "parser_registry.h",
    ],
    srcs = [
        "config_validator.cc",
        "parser_registry.cc",
    ],
    deps = [
        ":graph_config",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@graph_runtime//src/framework/public:types",
    ],
)
